SELECT TOP (1000) 
       c.[ContestNum]
      ,c.[ContestDesc]
      ,c.[Status]
      ,c.[ContestDateTime]
      ,c.[WagerCutoff]
      ,c.[ContestType]
      ,c.[ContestType2]
      ,c.[ContestType3]
      ,c.[Comments]
      ,c.[AdjWagersToFinal]
      ,c.[NumberOfContestants]
      ,c.[HorseRaceFlag]
      ,c.[ThresholdUnits]
      ,c.[XtoYLineRep]
      ,c.[ThresholdType]
      ,c.[FirstRotNum]
      ,c.[CircledMaxWager]
      ,c.[GradeDateTime]
      ,c.[DailyFigureDate]
      ,c.[CorrelationID]
      ,c.[ApplyWhaleLimit]
      ,c.[DerivativeId]
      ,c.[MaxExposure]
      ,c.[CategoryId]
      ,c.[GradingUnitTypeId]
      ,c.[MarginStrategyId]
      ,c.[OpenedAt]
      ,c.[HasDeadHeatRule]
      ,c.[HasEachWayRule]
      ,c.[EachWayPayoutMultiplier]
      ,c.[EachWayPaidPositions]
      ,c.[ChangedBy]
  FROM [asidb].[dbo].[tbContest] c
  WHERE c.ContestNum = 1037852309
