SELECT TOP (1000) 
       gl.[GameNum]
      ,gl.[PeriodNumber]
      ,gl.[Store]
      ,gl.[CustProfile]
      ,gl.[LineSeq]
      ,gl.[FavoredTeamID]
      ,gl.[Spread]
      ,gl.[SpreadAdj1]
      ,gl.[SpreadAdj2]
      ,gl.[AllowBuyOnSpread]
      ,gl.[TotalPoints]
      ,gl.[TtlPtsAdj1]
      ,gl.[TtlPtsAdj2]
      ,gl.[AllowBuyOnPoints]
      ,gl.[MoneyLine1]
      ,gl.[MoneyLine2]
      ,gl.[PeriodDescription]
      ,gl.[Team1TotalPoints]
      ,gl.[Team1TtlPtsAdj1]
      ,gl.[Team1TtlPtsAdj2]
      ,gl.[Team2TotalPoints]
      ,gl.[Team2TtlPtsAdj1]
      ,gl.[Team2TtlPtsAdj2]
      ,gl.[PuckLine]
      ,gl.[OnlineFeedSpread]
      ,gl.[OnlineFeedMoneyLine]
      ,gl.[OnlineFeedTotalPoints]
      ,gl.[TeamActionLinePos]
      ,gl.[KeepOpenFlag]
      ,gl.[LastSpreadChange]
      ,gl.[LastMoneyLineChange]
      ,gl.[LastTtlPtsChange]
      ,gl.[LastTeamPtsChange]
      ,gl.[PeriodWagerCutoff]
      ,gl.[MoneyLineDraw]
      ,gl.[CircledMaxWagerSpread]
      ,gl.[CircledMaxWagerTotal]
      ,gl.[CircledMaxWagerMoneyLine]
      ,gl.[CircledMaxWagerTeamTotal]
      ,gl.[Team1IDScore]
      ,gl.[Team2IDScore]
      ,gl.[RestOfGameSpread]
      ,gl.[TWSpread1]
      ,gl.[TWBallPercent1]
      ,gl.[TWSpreadAdj1]
      ,gl.[TWSpreadAdj2]
      ,gl.[LastTWSpreadChange]
      ,gl.[PeriodStatus]
      ,gl.[Team1IDRedCards]
      ,gl.[Team2IDRedCards]
      ,'--------------------[Game]---------------------' as "----------------------[Game]---------------------"
      ,g.*
  FROM [asidb].[dbo].[tbGameLine] gl
        INNER JOIN [asidb].[dbo].[tbGame] g ON gl.GameNum = g.GameNum
    WHERE 1=1
			AND g.GameNum = 1039826047 --1037257948
            AND gl.PeriodNumber = 0
