SELECT TOP (1000) 
       ngl.[LineIndex]
      ,ngl.[GameNum]
      ,ngl.[PeriodNumber]
      ,ngl.[Store]
      ,ngl.[CustProfile]
      ,ngl.[LineSeq]
      ,ngl.[FavoredTeamID]
      ,ngl.[Spread]
      ,ngl.[SpreadAdj1]
      ,ngl.[SpreadAdj2]
      ,ngl.[AllowBuyOnSpread]
      ,ngl.[TotalPoints]
      ,ngl.[TtlPtsAdj1]
      ,ngl.[TtlPtsAdj2]
      ,ngl.[AllowBuyOnPoints]
      ,ngl.[MoneyLine1]
      ,ngl.[MoneyLine2]
      ,ngl.[PeriodDescription]
      ,ngl.[Team1TotalPoints]
      ,ngl.[Team1TtlPtsAdj1]
      ,ngl.[Team1TtlPtsAdj2]
      ,ngl.[Team2TotalPoints]
      ,ngl.[Team2TtlPtsAdj1]
      ,ngl.[Team2TtlPtsAdj2]
      ,ngl.[PuckLine]
      ,ngl.[OnlineFeedSpread]
      ,ngl.[OnlineFeedMoneyLine]
      ,ngl.[OnlineFeedTotalPoints]
      ,ngl.[TeamActionLinePos]
      ,ngl.[KeepOpenFlag]
      ,ngl.[LastSpreadChange]
      ,ngl.[LastMoneyLineChange]
      ,ngl.[LastTtlPtsChange]
      ,ngl.[LastTeamPtsChange]
      ,ngl.[PeriodWagerCutoff]
      ,ngl.[MoneyLineDraw]
      ,ngl.[CircledMaxWagerSpread]
      ,ngl.[CircledMaxWagerTotal]
      ,ngl.[CircledMaxWagerMoneyLine]
      ,ngl.[CircledMaxWagerTeamTotal]
      ,ngl.[ChangeDateTime]
      ,ngl.[Team1IDScore]
      ,ngl.[Team2IDScore]
      ,ngl.[RestOfGameSpread]
      ,ngl.[TWSpread1]
      ,ngl.[TWBallPercent1]
      ,ngl.[TWSpreadAdj1]
      ,ngl.[TWSpreadAdj2]
      ,ngl.[LastTWSpreadChange]
      ,ngl.[PeriodStatus]
      ,ngl.[Team1IDRedCards]
      ,ngl.[Team2IDRedCards]
      ,'--------------------[Game]---------------------' as "----------------------[Game]---------------------"
      ,g.*
  FROM [asidb].[dbo].[tbNewGameLine] ngl
        INNER JOIN [asidb].[dbo].[tbGame] g ON ngl.GameNum = g.GameNum
  WHERE 1=1
    AND ngl.GameNum = 1039709002
    AND ngl.PeriodNumber = 0
